# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/safe/nixos/root";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "rpool/local/storage/nixos/nix";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/safe/storage/home";
      fsType = "zfs";
    };

  fileSystems."/storage/secrets" =
    { device = "rpool/safe/storage/secrets";
      fsType = "zfs";
    };

  fileSystems."/storage/vm" =
    { device = "rpool/safe/storage/vm";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F211-3513";
      fsType = "vfat";
    };

  fileSystems."/boot-fallback" =
    { device = "/dev/disk/by-uuid/F211-A181";
      fsType = "vfat";
    };

  swapDevices = [ ];

}
