#!/usr/bin/env bash
#cd /nix
#git clone https://github.com/nixos/nixpkgs
#cd /nix/nixpkgs/
#git checkout tags/21.05 -b 21.05
#git cherry-pick adc368d2fc7dd74beb8486ff72880ed0212abb0d
#cd /etc/nixos
export NIXPKGS=/nix/nixpkgs
nixos-rebuild -I nixpkgs=$NIXPKGS test
